import type { FitnessClass } from "./classTypes";

export const classRows: FitnessClass[] = [
  {
    id: "1",
    className: "Boxing",
    instructor: "Mg Kyaw",
    startTime: "6:30 AM",
    capacity: 20,
    bookedCount: 12,
    status: "Scheduled",
    attendees: [
      { id: "a1", name: "Su Su", paymentType: "Membership", bookingStatus: "Checked-in" },
      { id: "a2", name: "Mya Mya", paymentType: "Package", bookingStatus: "Booked" },
    ],
  },
  {
    id: "2",
    className: "Yoga",
    instructor: "Su Su",
    startTime: "8:00 AM",
    capacity: 15,
    bookedCount: 15,
    status: "Full",
    attendees: [{ id: "a3", name: "Phyu Phyu", paymentType: "One-time", bookingStatus: "Checked-in" }],
  },
  {
    id: "3",
    className: "Gym",
    instructor: "Mg Mya",
    startTime: "9:15 AM",
    capacity: 25,
    bookedCount: 8,
    status: "Cancelled",
    attendees: [],
  },
  {
    id: "4",
    className: "Boxing",
    instructor: "Mya Mya",
    startTime: "10:00 AM",
    capacity: 20,
    bookedCount: 5,
    status: "Scheduled",
    attendees: [{ id: "a4", name: "Mg Kyaw", paymentType: "Package", bookingStatus: "Booked" }],
  },
  {
    id: "5",
    className: "Yoga",
    instructor: "Phyu Phyu",
    startTime: "11:00 AM",
    capacity: 15,
    bookedCount: 10,
    status: "Scheduled",
    attendees: [
      { id: "a5", name: "Su Su", paymentType: "Membership", bookingStatus: "Checked-in" },
      { id: "a6", name: "Mg Mya", paymentType: "One-time", bookingStatus: "No-show" },
    ],
  },
  {
    id: "6",
    className: "Gym",
    instructor: "Mg Kyaw",
    startTime: "1:00 PM",
    capacity: 25,
    bookedCount: 20,
    status: "Scheduled",
    attendees: [{ id: "a7", name: "Mya Mya", paymentType: "Membership", bookingStatus: "Checked-in" }],
  },
  {
    id: "7",
    className: "Boxing",
    instructor: "Su Su",
    startTime: "2:30 PM",
    capacity: 20,
    bookedCount: 18,
    status: "Scheduled",
    attendees: [{ id: "a8", name: "Phyu Phyu", paymentType: "Package", bookingStatus: "Booked" }],
  },
];
